[package]
authors = ["Doug Goldstein <cardoe@cardoe.com>"]
description = "Logger that logs to stderr based on verbosity specified"
documentation = "https://docs.rs/stderrlog/"
homepage = "https://github.com/cardoe/stderrlog-rs"
keywords = ["log", "loglevel", "logging", "stderr", "stderrlog"]
categories = ["development-tools::debugging"]
license = "MIT/Apache-2.0"
name = "stderrlog"
readme = "README.md"
changelog = "CHANGELOG.md"
repository = "https://github.com/cardoe/stderrlog-rs"
version = "0.3.0"

[dependencies]
chrono = "0.4"
log = { version = "0.4.1", features = ["std"] }
termcolor = "0.3.3"
thread_local = "0.3"

[dev-dependencies]
clap = "2"
docopt = "0.6"
rustc-serialize = "0.3"
libc = "0.2"
